spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/spacesync
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update